# Generated by Django 4.0.3 on 2022-04-10 18:55

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=32, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=128, verbose_name='Descrição')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('foto', stdimage.models.StdImageField(upload_to='vendedores/e111d394-e66e-44e2-9ddc-60fff7ff7973.jpg', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('modelo', models.CharField(max_length=64, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('foto', stdimage.models.StdImageField(upload_to='carros/d932c764-fbc8-485e-a284-92a9442f21e3.jpg', verbose_name='Foto')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque?')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marcacarro', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
