# Generated by Django 4.0.3 on 2022-04-10 19:22

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Foto'),
        ),
    ]
